name: CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 8位commit id
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 8

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: registry.cn-shenzhen.aliyuncs.com
          username: ${{ secrets.DOCKER_REG_USERNAME }}
          password: ${{ secrets.DOCKER_REG_PASSWORD }}

      - name: Build and Push Docker images
        id: docker_build
        uses: docker/build-push-action@v3
        env:
          OJ_JUDGER_VERSION: ${{ github.ref_name }}-${{ steps.short-sha.outputs.sha }}
        with:
          context: ./
          push: true
          build-args: |
            OJ_JUDGER_VERSION=${{ env.OJ_BE_VERSION }}
          tags: |
            registry.cn-shenzhen.aliyuncs.com/szuoj/judge_server:latest
            registry.cn-shenzhen.aliyuncs.com/szuoj/judge_server:${{ env.OJ_JUDGER_VERSION }}
          # https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
